// ctd_manager — DDS adaptor for the VALEPORT Bathy2 CTD sensor (xl300-dds-v2
// DDS_Topic_Contract.md §5/§6: `sensors/ctd` -> CtdSample, `health/<node>` ->
// Heartbeat). Config-driven, transport-abstracted design ported from the
// real, currently-running MQTT prototype at
// workspace-mqtt/xl300-ctd-manager/ — same JSON config shape, same ITransport
// pool, same real VALEPORT Bathy2 14-field parser (CtdParser.hpp). The one
// structural swap: DDS pub replaces MQTT pub. Pure sensor-in publisher — no
// subscriptions, no failover gate, no sd_notify (this isn't a systemd unit).
//
//   CtdManager::receiveLoop : ctd_rx transport (config: input_channels.ctd_rx) ->
//                             parses real VALEPORT Bathy2 frames -> latestSnapshot();
//                             also sends the device's startup configuration
//                             commands (output_channels.commands), if configured.
//   (this file) publishLoop : latestSnapshot()+health() -> sensors/ctd (`mission`
//                             partition, SENSOR QoS) + health/<node> (`diagnostics`
//                             partition, HEALTH QoS, node="ctd_manager"), each at
//                             its own publish_interval_ms from dds.topics.pub[].
//
// Run:  ./ctd_manager ctd_config.json
#include <fastdds/dds/domain/DomainParticipant.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/publisher/DataWriter.hpp>
#include <fastdds/dds/publisher/Publisher.hpp>
#include <fastdds/dds/topic/TypeSupport.hpp>

// Generated by uuv_interfaces/gen.sh from its xl300-dds-v2 submodule's FULL idl/
// tree -- committed there, not regenerated by this app (see
// uuv_interfaces/README.md). Every type in the contract is available via
// uuv_interfaces/generated/*.h; this app only #includes the two it uses.
#include "ctd.h"
#include "ctdPubSubTypes.h"
#include "health.h"
#include "healthPubSubTypes.h"
#include "contract_constants.hpp"

#include "Config.hpp"
#include "CtdManager.hpp"
#include "Logger.hpp"
#include "DdsNode.hpp"

#include <atomic>
#include <chrono>
#include <csignal>
#include <iostream>
#include <thread>

using namespace eprosima::fastdds::dds;
using namespace std::chrono;

static std::atomic<bool> g_run{true};
static void on_sig(int) { g_run = false; }

#define MOD "main"
#define NODE_NAME "ctd_manager"

static LogLevel parseLogLevel(const std::string& s) {
    if (s == "error") return LogLevel::ERROR;
    if (s == "warn")  return LogLevel::WARN;
    if (s == "info")  return LogLevel::INFO;
    return LogLevel::DEBUG;
}

// Maps CtdManager::health()'s string vocabulary onto health.idl's HealthState.
// CtdManager never returns "error" (see its computeDeviceHealth doc), so
// HEALTH_ERROR is unreachable here — kept only for enum completeness.
static xl300::HealthState toHealthState(const std::string& h) {
    if (h == "ok")           return xl300::HEALTH_OK;
    if (h == "degraded")     return xl300::HEALTH_DEGRADED;
    if (h == "disabled")     return xl300::HEALTH_DISABLED;
    if (h == "disconnected") return xl300::HEALTH_DISCONNECTED;
    return xl300::HEALTH_ERROR;
}

int main(int argc, char** argv) {
    std::signal(SIGINT, on_sig);
    std::signal(SIGTERM, on_sig);

    Logger::init();
    if (argc < 2) {
        std::cerr << "usage: ctd_manager <ctd_config.json>\n";
        return 1;
    }
    AppConfig cfg;
    try {
        cfg = AppConfig::fromFile(argv[1]);
    } catch (const std::exception& e) {
        std::cerr << "FATAL: " << e.what() << "\n";
        return 1;
    }
    Logger::setEnabled(cfg.debug.enabled);
    Logger::setLevel(parseLogLevel(cfg.debug.level));

    // Contract facts (domain id, topic name strings, QoS profile names,
    // partition names) come from xl300::contract -- generated by
    // uuv_interfaces from xl300-dds-v2's own config/*.yaml, not from this
    // app's JSON config. See Config.hpp's DdsTopicConfig comment for why:
    // a typo'd topic string in ctd_config.json would otherwise silently
    // desync this app from everyone else's understanding of "sensors/ctd",
    // with no error at all.
    using namespace xl300::contract;

    std::cout << "[ctd_manager] config=" << argv[1] << " sensor=" << cfg.sensor
              << " domain=" << kDomainId
              << " transports=" << cfg.sensor_config.transports.size()
              << " devices=" << cfg.sensor_config.devices.size() << "\n";

    auto* dpf = DomainParticipantFactory::get_instance();
    // "xl300_domain10" matches uuv_interfaces/xl300-dds-v2/qos/xl300_profiles.xml's
    // participant profile. uuv_common::createParticipant() falls back to a plain
    // domain-id participant if the profiles file isn't loaded (e.g. dev run
    // without FASTRTPS_DEFAULT_PROFILES_FILE set).
    DomainParticipant* dp = uuv_common::createParticipant("xl300_domain10", kDomainId);
    if (!dp) { std::cerr << "FATAL: no participant\n"; return 1; }

    TypeSupport t_ctd(new xl300::CtdSamplePubSubType()); t_ctd.register_type(dp);
    TypeSupport t_hb(new xl300::HeartbeatPubSubType());  t_hb.register_type(dp);

    // ctd_config.json's dds.topics{} (looked up by "name") only ever supplies
    // publish_interval_ms/debug for these two -- never the topic/QoS/partition
    // facts themselves.
    const DdsTopicConfig* ctd_topic_cfg = cfg.dds.find("sensors_ctd");
    const DdsTopicConfig* hb_topic_cfg  = cfg.dds.find("health");

    Topic* tp_ctd = dp->create_topic(topics::kSensorsCtd.topic, t_ctd.get_type_name(), TOPIC_QOS_DEFAULT);
    Topic* tp_hb  = dp->create_topic(topics::kHealth.topic,     t_hb.get_type_name(),  TOPIC_QOS_DEFAULT);

    PublisherQos pq_mission = PUBLISHER_QOS_DEFAULT;
    pq_mission.partition().push_back(topics::kSensorsCtd.partition);
    Publisher* pub_mission = dp->create_publisher(pq_mission);       // sensors/ctd
    PublisherQos pq_diag = PUBLISHER_QOS_DEFAULT;
    pq_diag.partition().push_back(topics::kHealth.partition);
    Publisher* pub_diag = dp->create_publisher(pq_diag);             // health/<node>

    DataWriter* w_ctd = uuv_common::createWriter(pub_mission, tp_ctd, topics::kSensorsCtd.qos_profile);
    DataWriter* w_hb  = uuv_common::createWriter(pub_diag,    tp_hb,  topics::kHealth.qos_profile);

    CtdManager ctd_mgr(cfg);
    ctd_mgr.start();

    int ctd_interval_ms = ctd_topic_cfg && ctd_topic_cfg->publish_interval_ms > 0 ? ctd_topic_cfg->publish_interval_ms : 1000;
    int hb_interval_ms  = hb_topic_cfg  && hb_topic_cfg->publish_interval_ms  > 0 ? hb_topic_cfg->publish_interval_ms  : 1000;
    bool ctd_debug = ctd_topic_cfg && ctd_topic_cfg->debug;
    bool hb_debug  = hb_topic_cfg  && hb_topic_cfg->debug;

    auto last_ctd = steady_clock::now() - hours(1);
    auto last_hb  = steady_clock::now() - hours(1);

    LOG_INF(MOD, "publish loop: %s @ %dms, %s @ %dms",
            topics::kSensorsCtd.topic, ctd_interval_ms, topics::kHealth.topic, hb_interval_ms);

    while (g_run) {
        auto now = steady_clock::now();

        if (now - last_ctd >= milliseconds(ctd_interval_ms)) {
            last_ctd = now;
            CtdSnapshot snap = ctd_mgr.latestSnapshot();
            const auto& devices = cfg.sensor_config.devices;
            bool device_publishes = !devices.empty() && devices[0].publish_enabled;
            if (snap.is_valid && device_publishes) {
                bool stale = false;
                if (!devices[0].publish_stale_data) {
                    auto rxIt = devices[0].input_channels.find("ctd_rx");
                    int timeout_ms = rxIt != devices[0].input_channels.end()
                                         ? rxIt->second.data_timeout_ms : 2000;
                    auto age_ms = duration_cast<milliseconds>(
                                      system_clock::now() - snap.timestamp).count();
                    stale = age_ms >= timeout_ms;
                }
                if (!stale) {
                    const CtdData& d = snap.data;
                    xl300::CtdSample s{};
                    s.header().ts(uuv_common::epochMs(system_clock::now()));
                    s.header().data_ts(uuv_common::epochMs(snap.timestamp));
                    s.header().sender(NODE_NAME);
                    s.header().schema_version(1);
                    s.device_id(static_cast<uint16_t>(devices[0].id));
                    s.device_name(devices[0].name);
                    s.valid(true);
                    s.date(d.date);
                    s.time(d.time);
                    s.conductivity(d.conductivity);
                    s.pressure(d.pressure_selected);
                    s.water_temp(d.water_temp);
                    s.altimeter_height(d.altimeter_height);
                    s.sound_vel(d.sound_velocity);
                    s.pressure_aux(d.aux_pressure);
                    s.depth(d.depth);
                    s.total_depth(d.total_depth);
                    s.point_density(d.point_density);
                    s.profile_density(d.profile_density);
                    s.salinity(d.salinity);
                    s.pressure_baro(d.barometric_pressure);
                    w_ctd->write(&s);
                    if (ctd_debug)
                        LOG_DBG(MOD, "%s TX depth=%.2f temp=%.2f sal=%.2f",
                                topics::kSensorsCtd.topic, s.depth(), s.water_temp(), s.salinity());
                }
            }
        }

        if (now - last_hb >= milliseconds(hb_interval_ms)) {
            last_hb = now;
            CtdSnapshot snap = ctd_mgr.latestSnapshot();
            long data_age_ms = -1;
            if (snap.is_valid)
                data_age_ms = static_cast<long>(duration_cast<milliseconds>(
                    system_clock::now() - snap.timestamp).count());

            xl300::Heartbeat hb{};
            hb.header().ts(uuv_common::epochMs(system_clock::now()));
            hb.header().data_ts(0);
            hb.header().sender(NODE_NAME);
            hb.header().schema_version(1);
            hb.node(NODE_NAME);
            hb.status(toHealthState(ctd_mgr.health()));
            static uint32_t seq = 0;
            hb.seq(seq++);
            hb.data_age_ms(data_age_ms);
            w_hb->write(&hb);
            if (hb_debug)
                LOG_DBG(MOD, "%s TX status=%d seq=%u age_ms=%ld",
                        topics::kHealth.topic, (int)hb.status(), seq - 1, data_age_ms);
        }

        std::this_thread::sleep_for(milliseconds(20));
    }

    ctd_mgr.stop();
    dpf->delete_participant(dp);
    std::cout << "[ctd_manager] stopped\n";
    return 0;
}
