#include "CtdApp.hpp"

#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/publisher/Publisher.hpp>
#include <fastdds/dds/topic/Topic.hpp>

// Generated by uuv_interfaces/gen.sh from its xl300-dds-v2 submodule's FULL idl/
// tree -- committed there, not regenerated by this app (see
// uuv_interfaces/README.md). Every type in the contract is available via
// uuv_interfaces/generated/*.h; this app only #includes the two it uses.
#include "ctd.h"
#include "ctdPubSubTypes.h"
#include "health.h"
#include "healthPubSubTypes.h"
#include "contract_constants.hpp"

#include "DdsNode.hpp"
#include "Logger.hpp"

#include <iostream>

using namespace eprosima::fastdds::dds;
using namespace std::chrono;

#define MOD "CtdApp"
#define NODE_NAME "ctd_manager"

static LogLevel parseLogLevel(const std::string &s)
{
    if (s == "error")
        return LogLevel::ERROR;
    if (s == "warn")
        return LogLevel::WARN;
    if (s == "info")
        return LogLevel::INFO;
    return LogLevel::DEBUG;
}

// Maps CtdManager::health()'s string vocabulary onto health.idl's HealthState.
// CtdManager never returns "error" (see its computeDeviceHealth doc), so
// HEALTH_ERROR is unreachable here — kept only for enum completeness.
static xl300::HealthState toHealthState(const std::string &h)
{
    if (h == "ok")
        return xl300::HEALTH_OK;
    if (h == "degraded")
        return xl300::HEALTH_DEGRADED;
    if (h == "disabled")
        return xl300::HEALTH_DISABLED;
    if (h == "disconnected")
        return xl300::HEALTH_DISCONNECTED;
    return xl300::HEALTH_ERROR;
}

CtdApp::~CtdApp() { stop(); }

bool CtdApp::initialize(const std::string &configPath)
{
    try
    {
        cfg_ = AppConfig::fromFile(configPath);
    }
    catch (const std::exception &e)
    {
        std::cerr << "FATAL: " << e.what() << "\n";
        return false;
    }
    Logger::setEnabled(cfg_.debug.enabled);
    Logger::setLevel(parseLogLevel(cfg_.debug.level));

    // Contract facts (domain id, topic name strings, QoS profile names,
    // partition names) come from xl300::contract -- generated by
    // uuv_interfaces from xl300-dds-v2's own config/*.yaml, not from this
    // app's JSON config. See Config.hpp's DdsTopicConfig comment for why:
    // a typo'd topic string in ctd_config.json would otherwise silently
    // desync this app from everyone else's understanding of "sensors/ctd",
    // with no error at all.
    using namespace xl300::contract;

    std::cout << "[ctd_manager] config=" << configPath << " sensor=" << cfg_.sensor << " domain=" << kDomainId
              << " transports=" << cfg_.sensor_config.transports.size()
              << " devices=" << cfg_.sensor_config.devices.size() << "\n";

    // "xl300_domain10" matches uuv_interfaces/xl300-dds-v2/qos/xl300_profiles.xml's
    // participant profile. uuv_common::createParticipant() falls back to a plain
    // domain-id participant if the profiles file isn't loaded (e.g. dev run
    // without FASTRTPS_DEFAULT_PROFILES_FILE set).
    dp_ = uuv_common::createParticipant("xl300_domain10", kDomainId);
    if (!dp_)
    {
        std::cerr << "FATAL: no participant\n";
        return false;
    }

    t_ctd_ = TypeSupport(new xl300::CtdSamplePubSubType());
    t_ctd_.register_type(dp_);
    t_hb_ = TypeSupport(new xl300::HeartbeatPubSubType());
    t_hb_.register_type(dp_);

    // ctd_config.json's dds.topics{} (looked up by "name") only ever supplies
    // publish_interval_ms/debug for these two -- never the topic/QoS/partition
    // facts themselves.
    const DdsTopicConfig *ctd_topic_cfg = cfg_.dds.find("sensors_ctd");
    const DdsTopicConfig *hb_topic_cfg = cfg_.dds.find("health");

    // A dds.topics.pub[] entry whose "name" doesn't match either known key is
    // silently ignored otherwise (find() returns nullptr, caller falls back to
    // defaults) -- warn so a typo/rename in the JSON doesn't go unnoticed.
    for (const auto &t : cfg_.dds.pub_topics)
        if (t.name != "sensors_ctd" && t.name != "health")
            LOG_WRN(MOD,
                    "dds.topics.pub[] entry with unrecognized name '%s' ignored "
                    "(expected 'sensors_ctd' or 'health')",
                    t.name.c_str());
    if (!ctd_topic_cfg)
        LOG_WRN(MOD, "no dds.topics.pub[] entry named 'sensors_ctd' -- using defaults");
    if (!hb_topic_cfg)
        LOG_WRN(MOD, "no dds.topics.pub[] entry named 'health' -- using defaults");

    Topic *tp_ctd = dp_->create_topic(topics::kSensorsCtd.topic, t_ctd_.get_type_name(), TOPIC_QOS_DEFAULT);
    Topic *tp_hb = dp_->create_topic(topics::kHealth.topic, t_hb_.get_type_name(), TOPIC_QOS_DEFAULT);

    PublisherQos pq_mission = PUBLISHER_QOS_DEFAULT;
    pq_mission.partition().push_back(topics::kSensorsCtd.partition);
    Publisher *pub_mission = dp_->create_publisher(pq_mission); // sensors/ctd
    PublisherQos pq_diag = PUBLISHER_QOS_DEFAULT;
    pq_diag.partition().push_back(topics::kHealth.partition);
    Publisher *pub_diag = dp_->create_publisher(pq_diag); // health/<node>

    w_ctd_ = uuv_common::createWriter(pub_mission, tp_ctd, topics::kSensorsCtd.qos_profile);
    w_hb_ = uuv_common::createWriter(pub_diag, tp_hb, topics::kHealth.qos_profile);

    const auto &devices = cfg_.sensor_config.devices;
    publish_on_data_rx_ = !devices.empty() && devices[0].publish_on_data_rx;
    ctd_interval_ms_ =
        ctd_topic_cfg && ctd_topic_cfg->publish_interval_ms > 0 ? ctd_topic_cfg->publish_interval_ms : 1000;
    hb_interval_ms_ = hb_topic_cfg && hb_topic_cfg->publish_interval_ms > 0 ? hb_topic_cfg->publish_interval_ms : 1000;
    ctd_debug_ = ctd_topic_cfg && ctd_topic_cfg->debug;
    hb_debug_ = hb_topic_cfg && hb_topic_cfg->debug;

    ctd_mgr_ = std::make_unique<CtdManager>(cfg_);
    return true;
}

void CtdApp::start()
{
    if (running_ || !ctd_mgr_)
        return;
    running_ = true;
    ctd_mgr_->start();
    publish_thread_ = std::thread(&CtdApp::publishLoop, this);
    LOG_INF(MOD, "publish loop: %s @ %s, %s @ %dms", xl300::contract::topics::kSensorsCtd.topic,
            publish_on_data_rx_ ? "publish_on_data_rx (per frame)" : (std::to_string(ctd_interval_ms_) + "ms").c_str(),
            xl300::contract::topics::kHealth.topic, hb_interval_ms_);
}

void CtdApp::stop()
{
    if (!running_)
        return;
    running_ = false;
    if (publish_thread_.joinable())
        publish_thread_.join();
    if (ctd_mgr_)
        ctd_mgr_->stop();
    if (dp_)
    {
        DomainParticipantFactory::get_instance()->delete_participant(dp_);
        dp_ = nullptr;
    }
}

void CtdApp::publishLoop()
{
    auto last_ctd = steady_clock::now() - hours(1);
    auto last_hb = steady_clock::now() - hours(1);

    while (running_)
    {
        auto now = steady_clock::now();

        if (publish_on_data_rx_)
        {
            // publish_interval_ms is ignored entirely in this mode -- matches
            // the real MQTT ctd_manager's devices[].publish_on_data_rx exactly
            // (see Config.hpp's comment). Detected via CtdManager's cumulative
            // packet counter rather than a callback: this loop already polls
            // at 20ms, well under the device's fastest configured rate.
            uint64_t pkt_rx = ctd_mgr_->stats().pkt_rx;
            if (pkt_rx != last_published_pkt_rx_)
            {
                last_published_pkt_rx_ = pkt_rx;
                publishCtdSampleIfFresh(ctd_mgr_->latestSnapshot());
            }
        }
        else if (now - last_ctd >= milliseconds(ctd_interval_ms_))
        {
            last_ctd = now;
            publishCtdSampleIfFresh(ctd_mgr_->latestSnapshot());
        }

        if (now - last_hb >= milliseconds(hb_interval_ms_))
        {
            last_hb = now;
            publishHeartbeat();
        }

        std::this_thread::sleep_for(milliseconds(20));
    }
}

void CtdApp::publishCtdSampleIfFresh(const CtdSnapshot &snap)
{
    const auto &devices = cfg_.sensor_config.devices;
    bool device_publishes = !devices.empty() && devices[0].publish_enabled;
    if (!snap.is_valid || !device_publishes)
        return;

    bool stale = false;
    if (!devices[0].publish_stale_data)
    {
        auto rxIt = devices[0].input_channels.find("ctd_rx");
        int timeout_ms = rxIt != devices[0].input_channels.end() ? rxIt->second.data_timeout_ms : 2000;
        auto age_ms = duration_cast<milliseconds>(system_clock::now() - snap.timestamp).count();
        stale = age_ms >= timeout_ms;
    }
    if (stale)
        return;

    const CtdData &d = snap.data;
    xl300::CtdSample s{};
    s.header().ts(uuv_common::epochMs(system_clock::now()));
    s.header().data_ts(uuv_common::epochMs(snap.timestamp));
    s.header().sender(NODE_NAME);
    s.header().schema_version(1);
    s.device_id(static_cast<uint16_t>(devices[0].id));
    s.device_name(devices[0].name);
    s.valid(true);
    s.date(d.date);
    s.time(d.time);
    s.conductivity(d.conductivity);
    s.pressure(d.pressure_selected);
    s.water_temp(d.water_temp);
    s.altimeter_height(d.altimeter_height);
    s.sound_vel(d.sound_velocity);
    s.pressure_aux(d.aux_pressure);
    s.depth(d.depth);
    s.total_depth(d.total_depth);
    s.point_density(d.point_density);
    s.profile_density(d.profile_density);
    s.salinity(d.salinity);
    s.pressure_baro(d.barometric_pressure);
    w_ctd_->write(&s);
    if (ctd_debug_)
        LOG_DBG(MOD, "%s TX depth=%.2f temp=%.2f sal=%.2f", xl300::contract::topics::kSensorsCtd.topic, s.depth(),
                s.water_temp(), s.salinity());
}

void CtdApp::publishHeartbeat()
{
    CtdSnapshot snap = ctd_mgr_->latestSnapshot();
    long data_age_ms = -1;
    if (snap.is_valid)
        data_age_ms = static_cast<long>(duration_cast<milliseconds>(system_clock::now() - snap.timestamp).count());

    xl300::Heartbeat hb{};
    hb.header().ts(uuv_common::epochMs(system_clock::now()));
    hb.header().data_ts(0);
    hb.header().sender(NODE_NAME);
    hb.header().schema_version(1);
    hb.node(NODE_NAME);
    hb.status(toHealthState(ctd_mgr_->health()));
    hb.seq(hb_seq_++);
    hb.data_age_ms(data_age_ms);
    w_hb_->write(&hb);
    if (hb_debug_)
        LOG_DBG(MOD, "%s TX status=%d seq=%u age_ms=%ld", xl300::contract::topics::kHealth.topic, (int)hb.status(),
                hb_seq_ - 1, data_age_ms);
}
